server:
  port: 8080

spring:
  cache:
    type: redis
  redis:
    host: localhost
    port: 6379
  rabbitmq:
    host: localhost
    virtual-host: /
    port: 5672
    username: guest
    password: guest
    template:
      routing-key: rabbitmq.routingkey
      exchange: rabbitmq.exchange
      reply-timeout: 60000
      default-receive-queue: myQueue
  datasource:
    url: jdbc:postgresql://localhost:5432/my_db
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: postgresql
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

nba:
  player_url: http://www.balldontlie.io/api/v1/players/
  team_url: http://www.balldontlie.io/api/v1/teams/

self:
  students_url: http://127.0.0.1:8080/student