server:
  port: 8080

spring:
  cache:
    type: redis
  redis:
    host: localhost
    port: 6379
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    dynamic: true
    template:
      reply-timeout: 30000
  datasource:
    url: jdbc:postgresql://localhost:5432/my_db
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: postgresql
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  main:
    allow-bean-definition-overriding: true

nba:
  player_url: http://www.balldontlie.io/api/v1/players/
  team_url: http://www.balldontlie.io/api/v1/teams/

self:
  students_url: http://127.0.0.1:8080/student